/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stations */
        get: operations["list_stations_api_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearby Stations
         * @description Closest stations to a position (the browser's geolocation never leaves this request).
         */
        get: operations["nearby_stations_api_v1_stations_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/home-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home Check
         * @description Journeys home with stranding risk, weak point, Plan B, and the latest safe departure.
         */
        get: operations["home_check_api_v1_journeys_home_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/deadline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deadline
         * @description The latest departure that arrives by ``arrive_by`` with at least ``confidence``.
         */
        get: operations["deadline_api_v1_journeys_deadline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Current delays for the trains of a journey (DB Timetables API, cached for 60 s).
         */
        get: operations["live_api_v1_journeys__journey_id__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Delete the account and every saved trip (GDPR Art. 17).
         */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v1_me_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_v1_me_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_v1_me_trips__trip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accuracy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accuracy
         * @description Live calibration (predictions matched with what really happened) and offline evaluation.
         */
        get: operations["accuracy_api_v1_accuracy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** DeadlineCheck */
        DeadlineCheck: {
            /** Departure */
            departure: string;
            /** Arrival */
            arrival: string;
            /** P Arrive By */
            p_arrive_by: number;
        };
        /** DeadlineResponse */
        DeadlineResponse: {
            origin: components["schemas"]["StationOut"];
            destination: components["schemas"]["StationOut"];
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Arrive By */
            arrive_by: string;
            /** Confidence */
            confidence: number;
            /** Regional Only */
            regional_only: boolean;
            /** Model Version */
            model_version: string;
            recommended?: components["schemas"]["JourneyOut"] | null;
            /** P Arrive By */
            p_arrive_by?: number | null;
            /** Checked */
            checked: components["schemas"]["DeadlineCheck"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeCheckResponse */
        HomeCheckResponse: {
            origin: components["schemas"]["StationOut"];
            destination: components["schemas"]["StationOut"];
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** After */
            after: string;
            /** Regional Only */
            regional_only: boolean;
            /** Model Version */
            model_version: string;
            /** Journeys */
            journeys: components["schemas"]["JourneyOut"][];
            latest_safe_departure?: components["schemas"]["JourneySummary"] | null;
            last_connection?: components["schemas"]["JourneySummary"] | null;
            /** Confidence */
            confidence: number;
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** JourneyOut */
        JourneyOut: {
            /** Id */
            id: string;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Departure */
            departure: string;
            /** Arrival */
            arrival: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Transfers */
            transfers: number;
            /** Legs */
            legs: components["schemas"]["LegOut"][];
            /** Connections */
            connections: components["schemas"]["TransferOut"][];
            risk: components["schemas"]["JourneyRisk"];
            weak_point?: components["schemas"]["TransferOut"] | null;
        };
        /** JourneyRisk */
        JourneyRisk: {
            /**
             * P Connections
             * @description Probability that every planned connection works
             */
            p_connections: number;
            /**
             * P Home
             * @description Probability to reach the destination tonight (incl. Plan B)
             */
            p_home: number;
            /** P Stranded */
            p_stranded: number;
            /**
             * P On Time
             * @description Probability to arrive at most 5 minutes after the planned arrival
             */
            p_on_time: number;
            /** Arrival P50 */
            arrival_p50?: string | null;
            /** Arrival P90 */
            arrival_p90?: string | null;
            /**
             * Level
             * @description low / medium / high
             */
            level: string;
        };
        /** JourneySummary */
        JourneySummary: {
            /** Departure */
            departure: string;
            /** Arrival */
            arrival: string;
            /** P Home */
            p_home: number;
            /** Journey Id */
            journey_id: string;
        };
        /** LegOut */
        LegOut: {
            /** Route */
            route: string;
            /** Category */
            category: string;
            /** Headsign */
            headsign?: string | null;
            /** Train Number */
            train_number?: string | null;
            origin: components["schemas"]["StopOut"];
            destination: components["schemas"]["StopOut"];
            /** Departure */
            departure: string;
            /** Arrival */
            arrival: string;
            /** Duration Minutes */
            duration_minutes: number;
            risk: components["schemas"]["LegRisk"];
        };
        /** LegRisk */
        LegRisk: {
            /**
             * Modelled
             * @description False for buses/trams, which are assumed to run on time
             */
            modelled: boolean;
            /** P Cancel */
            p_cancel: number;
            /** Departure Delay P50 */
            departure_delay_p50: number;
            /** Arrival Delay P50 */
            arrival_delay_p50: number;
            /** Arrival Delay P90 */
            arrival_delay_p90: number;
        };
        /** LiveJourneyResponse */
        LiveJourneyResponse: {
            /** Journey Id */
            journey_id: string;
            /** Available */
            available: boolean;
            /** Source */
            source: string;
            /** Legs */
            legs: components["schemas"]["LiveStop"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** LiveStop */
        LiveStop: {
            /** Station */
            station: string;
            /** Eva */
            eva: string;
            /** Train */
            train: string;
            /** Planned Departure */
            planned_departure?: string | null;
            /** Expected Departure */
            expected_departure?: string | null;
            /** Delay Minutes */
            delay_minutes?: number | null;
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
            /** Platform */
            platform?: string | null;
        };
        /** PlanBOut */
        PlanBOut: {
            /** Departure */
            departure: string;
            /** Arrival */
            arrival: string;
            /** Summary */
            summary: string;
            /** Transfers */
            transfers: number;
        };
        /** SavedTripIn */
        SavedTripIn: {
            /** Label */
            label?: string | null;
            /** From Station Id */
            from_station_id: string;
            /** To Station Id */
            to_station_id: string;
            /** Usual Departure */
            usual_departure?: string | null;
            /**
             * Regional Only
             * @default true
             */
            regional_only: boolean;
        };
        /** SavedTripOut */
        SavedTripOut: {
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** From Station Id */
            from_station_id: string;
            /** From Station Name */
            from_station_name: string;
            /** To Station Id */
            to_station_id: string;
            /** To Station Name */
            to_station_name: string;
            /** Usual Departure */
            usual_departure: string | null;
            /** Regional Only */
            regional_only: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StationOut */
        StationOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /**
             * Is Rail
             * @default false
             */
            is_rail: boolean;
        };
        /** StationsResponse */
        StationsResponse: {
            /** Query */
            query: string;
            /** Stations */
            stations: components["schemas"]["StationOut"][];
        };
        /** StopOut */
        StopOut: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Platform */
            platform?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TransferOut */
        TransferOut: {
            /**
             * Index
             * @description Index of the leg that has to be boarded (0 = first train)
             */
            index: number;
            /** Station */
            station: string;
            /** Planned Buffer Minutes */
            planned_buffer_minutes?: number | null;
            /** P Miss */
            p_miss: number;
            plan_b?: components["schemas"]["PlanBOut"] | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_api_v1_stations_get: {
        parameters: {
            query?: {
                search?: string;
                limit?: number;
                rail_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nearby_stations_api_v1_stations_nearby_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                limit?: number;
                rail_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_check_api_v1_journeys_home_check_get: {
        parameters: {
            query: {
                /** @description Station id or name */
                from: string;
                /** @description Station id or name */
                to: string;
                after: string;
                /** @description Service date (default: today) */
                date?: string | null;
                regional_only?: boolean;
                confidence?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deadline_api_v1_journeys_deadline_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                arrive_by: string;
                date?: string | null;
                confidence?: number;
                regional_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadlineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_journeys__journey_id__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveJourneyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_trips_api_v1_me_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTripOut"][];
                };
            };
        };
    };
    create_trip_api_v1_me_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedTripIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_v1_me_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accuracy_api_v1_accuracy_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
