"""initial schema

Revision ID: 793568e62036
Revises: 
Create Date: 2026-09-23 19:11:15.741750

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '793568e62036'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('monday', sa.Integer(), nullable=False),
    sa.Column('tuesday', sa.Integer(), nullable=False),
    sa.Column('wednesday', sa.Integer(), nullable=False),
    sa.Column('thursday', sa.Integer(), nullable=False),
    sa.Column('friday', sa.Integer(), nullable=False),
    sa.Column('saturday', sa.Integer(), nullable=False),
    sa.Column('sunday', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('calendar_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_dates', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_dates_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_dates_service_id'), ['service_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_months', sa.String(), nullable=True),
    sa.Column('test_months', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_key', sa.String(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('from_station_id', sa.String(), nullable=False),
    sa.Column('to_station_id', sa.String(), nullable=False),
    sa.Column('planned_departure', sa.String(), nullable=False),
    sa.Column('planned_arrival', sa.String(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('p_on_time', sa.Float(), nullable=False),
    sa.Column('p_stranded', sa.Float(), nullable=False),
    sa.Column('p_connections', sa.Float(), nullable=False),
    sa.Column('expected_delay', sa.Float(), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_journey_key'), ['journey_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_service_date'), ['service_date'], unique=False)

    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=True),
    sa.Column('route_short_name', sa.String(), nullable=False),
    sa.Column('route_long_name', sa.String(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('station_map',
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('eva', sa.String(), nullable=False),
    sa.Column('gtfs_name', sa.String(), nullable=False),
    sa.Column('db_name', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    with op.batch_alter_table('station_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_map_eva'), ['eva'], unique=False)

    op.create_table('stop_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_secs', sa.Integer(), nullable=False),
    sa.Column('departure_secs', sa.Integer(), nullable=False),
    sa.Column('pickup_type', sa.Integer(), nullable=False),
    sa.Column('drop_off_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stop_times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stop_times_stop_id'), ['stop_id'], unique=False)
        batch_op.create_index('ix_stop_times_trip_seq', ['trip_id', 'stop_sequence'], unique=False)

    op.create_table('stops',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('location_type', sa.Integer(), nullable=False),
    sa.Column('parent_station', sa.String(), nullable=True),
    sa.Column('platform_code', sa.String(), nullable=True),
    sa.Column('is_rail', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stop_id')
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_parent_station'), ['parent_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_stops_stop_name'), ['stop_name'], unique=False)

    op.create_table('train_stop_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=True),
    sa.Column('station_num', sa.Integer(), nullable=True),
    sa.Column('eva', sa.String(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('train_type', sa.String(), nullable=True),
    sa.Column('train_number', sa.String(), nullable=True),
    sa.Column('line_number', sa.String(), nullable=True),
    sa.Column('final_destination', sa.String(), nullable=True),
    sa.Column('service_date', sa.String(), nullable=True),
    sa.Column('arrival_planned', sa.DateTime(), nullable=True),
    sa.Column('arrival_actual', sa.DateTime(), nullable=True),
    sa.Column('departure_planned', sa.DateTime(), nullable=True),
    sa.Column('departure_actual', sa.DateTime(), nullable=True),
    sa.Column('arrival_delay', sa.Integer(), nullable=True),
    sa.Column('departure_delay', sa.Integer(), nullable=True),
    sa.Column('arrival_cancelled', sa.Boolean(), nullable=False),
    sa.Column('departure_cancelled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('train_stop_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_train_stop_history_ride_id'), ['ride_id'], unique=False)
        batch_op.create_index('ix_tsh_eva_time', ['eva', 'departure_planned'], unique=False)
        batch_op.create_index('ix_tsh_train_day', ['train_number', 'eva', 'service_date'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_stop_id', sa.String(), nullable=False),
    sa.Column('to_stop_id', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.Integer(), nullable=False),
    sa.Column('min_transfer_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_from_stop_id'), ['from_stop_id'], unique=False)

    op.create_table('trips',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('trip_headsign', sa.String(), nullable=True),
    sa.Column('trip_short_name', sa.String(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_service_id'), ['service_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('connections_held', sa.Boolean(), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('actual_arrival_delay', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_prediction_id'), ['prediction_id'], unique=True)

    op.create_table('saved_trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('from_station_id', sa.String(), nullable=False),
    sa.Column('from_station_name', sa.String(), nullable=False),
    sa.Column('to_station_id', sa.String(), nullable=False),
    sa.Column('to_station_name', sa.String(), nullable=False),
    sa.Column('usual_departure', sa.String(), nullable=True),
    sa.Column('regional_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_trips_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_trips_user_id'))

    op.drop_table('saved_trips')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_prediction_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_service_id'))
        batch_op.drop_index(batch_op.f('ix_trips_route_id'))

    op.drop_table('trips')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_from_stop_id'))

    op.drop_table('transfers')
    with op.batch_alter_table('train_stop_history', schema=None) as batch_op:
        batch_op.drop_index('ix_tsh_train_day')
        batch_op.drop_index('ix_tsh_eva_time')
        batch_op.drop_index(batch_op.f('ix_train_stop_history_ride_id'))

    op.drop_table('train_stop_history')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_stop_name'))
        batch_op.drop_index(batch_op.f('ix_stops_parent_station'))

    op.drop_table('stops')
    with op.batch_alter_table('stop_times', schema=None) as batch_op:
        batch_op.drop_index('ix_stop_times_trip_seq')
        batch_op.drop_index(batch_op.f('ix_stop_times_stop_id'))

    op.drop_table('stop_times')
    with op.batch_alter_table('station_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_map_eva'))

    op.drop_table('station_map')
    op.drop_table('routes')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_service_date'))
        batch_op.drop_index(batch_op.f('ix_predictions_journey_key'))

    op.drop_table('predictions')
    op.drop_table('model_versions')
    with op.batch_alter_table('calendar_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_dates_service_id'))
        batch_op.drop_index('ix_calendar_dates_date')

    op.drop_table('calendar_dates')
    op.drop_table('calendar')
    # ### end Alembic commands ###
